sudo: required

# We don't use these facilities, but they're lightweight:
language: C

services:
  - docker

before_install:
  # Normalize ownership UIDs between host and container so container can write:
  - sudo chown -R 1000 .
  - make docker_es

script:
  - docker-compose -f tooling/docker/docker-compose.yml run -e DXR_PROD=1 dev make test
